

class RandomGenerator{
	constructor(minValue, maxValue){
		this.minValue = minValue;
		this.maxValue = maxValue;
		if (minValue === undefined || maxValue === undefined){
			this.minValue = 1;
			this.maxValue = 10;
		}
		this.randomNumber = this.generate();
		//takes in the minimum and maximum values
		//if they are not defined, it sets the minimum to 1, and the max to 10
		//makes storage for the random number
	}
	generate(){
		this.randomNumber = Math.floor(Math.random() * this.maxValue) + this.minValue;
		//make a random value between the minimum and maximum values
		//and store the number into the storage from the constructor
	}
	getRange(){
		var values = {
            min: this.minValue,
            max: this.maxValue
		}
		return values;
		//return an object with min and max, min being the minimum value for the generator, max being the maximum value
		//returns a basic object literal
	}
	getNum(){
		return this.randomNumber;
		//return the random number that was generated by generate()
	}
}